/*
 * 大模型生成 - 由 testagent 自动生成，请勿手动修改
 * Generated by: testagent (AI-powered test generation)
 * Target:    com.example.Calculator#divide
 * Iteration: 5
 */
package com.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {

    private Calculator calculator;

    @BeforeEach
    public void setUp() {
        calculator = new Calculator();
    }

    @Test
    public void testDivide_exactDivision() {
        assertEquals(5, calculator.divide(10, 2));
    }

    @Test
    public void testDivide_resultIsOne() {
        assertEquals(1, calculator.divide(7, 7));
    }

    @Test
    public void testDivide_dividendIsZero() {
        assertEquals(0, calculator.divide(0, 3));
    }

    @Test
    public void testDivide_negativeNumbers() {
        assertEquals(-4, calculator.divide(-8, 2));
    }

    @Test
    public void testDivide_negativeDivisor() {
        assertEquals(-4, calculator.divide(8, -2));
    }

    @Test
    public void testDivide_integerTruncation() {
        assertEquals(3, calculator.divide(10, 3));
    }

    @Test
    public void testDivide_byZero_throwsArithmeticException() {
        assertThrows(ArithmeticException.class, () -> calculator.divide(10, 0));
    }
}