# -*- coding: utf-8 -*-
"""C++ Makefile test writing and command execution helpers."""

from __future__ import annotations

import logging
import os
import re
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

_MAKEFILE_MARKERS = ("Makefile", "makefile", "GNUmakefile")


def detect_build_tool(project_path: Path) -> str:
    """检测 C++ 项目的构建入口。

    功能简介：
        当前 C++ 执行器只支持带 `Makefile` 的项目，并要求项目提供
        `testagent-test` 目标供自动化测试调用。

    输入参数：
        project_path:
            C++ 项目根目录。

    返回值：
        str:
            固定返回 `make`。

    异常：
        FileNotFoundError:
            项目根目录下不存在 Makefile 时抛出。
    """
    for marker in _MAKEFILE_MARKERS:
        if (project_path / marker).is_file():
            return "make"
    raise FileNotFoundError(
        f"Makefile not found in {project_path}. "
        "C++ execution requires a Makefile target named 'testagent-test'."
    )


def _safe_target_fragment(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_") or "target"


def expected_test_file_path(
    project_path: Path,
    class_name: str,
    method_name: str,
    iteration: int,
) -> Path:
    """返回 C++ 生成测试文件路径。"""
    class_fragment = _safe_target_fragment(class_name)
    method_fragment = _safe_target_fragment(method_name)
    filename = f"{class_fragment}_{method_fragment}_iter{iteration}.cpp"
    return project_path / "tests" / "testagent" / "generated" / filename


def _make_banner(class_name: str, method_name: str, iteration: int) -> str:
    """构造 C++ 生成测试文件头部注释。"""
    return (
        "// Generated by: testagent (AI-powered test generation)\n"
        f"// Target: {class_name}#{method_name}\n"
        f"// Iteration: {iteration}\n"
    )


def write_test_file(
    test_code: str,
    project_path: Path,
    class_name: str,
    method_name: str,
    iteration: int,
) -> Path:
    """写入 C++ 生成测试文件。

    功能简介：
        将 LLM 生成的完整 C++ 测试源文件写入
        `tests/testagent/generated/`，并添加轻量 banner 标记。C++ 路径不合并
        人工测试文件，避免破坏已有项目测试布局。
    """
    dest = expected_test_file_path(project_path, class_name, method_name, iteration)
    dest.parent.mkdir(parents=True, exist_ok=True)
    content = f"{_make_banner(class_name, method_name, iteration)}\n{test_code.strip()}\n"
    dest.write_text(content, encoding="utf-8")
    logger.info("Wrote C++ test file: %s", dest)
    return dest


def build_make_command(project_path: Path, test_file: Path, report_dir: Path) -> list[str]:
    """构造 Makefile 测试执行命令。"""
    resolved_test_file = test_file.resolve()
    resolved_report_dir = report_dir.resolve()
    binary = resolved_report_dir / "test_binary"
    cxx = os.environ.get("CXX", "c++")
    return [
        "make",
        "testagent-test",
        f"TEST_FILE={resolved_test_file}",
        f"TEST_BINARY={binary}",
        f"REPORT_DIR={resolved_report_dir}",
        f"CXX={cxx} --coverage",
    ]


def run_build(project_path: Path, command: list[str], timeout: int = 300) -> tuple[int, str]:
    """执行 C++ 构建命令并返回退出码与输出。"""
    logger.info("Running C++ build: %s", " ".join(command))
    result = subprocess.run(
        command,
        cwd=project_path,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout,
        text=True,
    )
    return result.returncode, result.stdout
