# -*- coding: utf-8 -*-
"""Tests for C++ test executor support."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from testagent.executor import create_executor
from testagent.executor.cpp.builder import (
    build_make_command,
    detect_build_tool,
    expected_test_file_path,
    write_test_file,
)
from testagent.executor.cpp.runner import parse_make_result
from testagent.models import AnalysisContext, GeneratedTest, TargetMethod

PROJECT_ROOT = Path(__file__).resolve().parents[2]

CPP_TEST_CODE = """\
#include "shop/pricing_service.h"

#include <cassert>

int main() {
    return 0;
}
"""


def _context(class_name: str = "shop::PricingService", method_name: str = "finalPrice") -> AnalysisContext:
    return AnalysisContext(
        target=TargetMethod(
            class_name=class_name,
            method_name=method_name,
            method_signature="double PricingService::finalPrice(const Cart& cart) const { return 0.0; }",
            file_path=Path("/project/src/pricing_service.cpp"),
            class_source="class PricingService {};",
        ),
        dependencies=[],
        imports=['#include "shop/pricing_service.h"'],
        package="shop",
    )


def test_factory_creates_cpp_executor(tmp_path: Path):
    (tmp_path / "Makefile").touch()

    executor = create_executor("cpp", tmp_path, reports_dir=tmp_path / "reports")

    assert type(executor).__name__ == "CppTestExecutor"


def test_detects_makefile(tmp_path: Path):
    (tmp_path / "Makefile").touch()

    assert detect_build_tool(tmp_path) == "make"


def test_detect_build_tool_raises_without_makefile(tmp_path: Path):
    with pytest.raises(FileNotFoundError, match="Makefile"):
        detect_build_tool(tmp_path)


def test_expected_test_file_path_is_stable(tmp_path: Path):
    path = expected_test_file_path(tmp_path, "shop::PricingService", "finalPrice", 2)

    assert path == tmp_path / "tests" / "testagent" / "generated" / "shop_PricingService_finalPrice_iter2.cpp"


def test_write_test_file_adds_banner_and_keeps_cpp_code(tmp_path: Path):
    path = write_test_file(
        test_code=CPP_TEST_CODE,
        project_path=tmp_path,
        class_name="shop::PricingService",
        method_name="finalPrice",
        iteration=1,
    )

    content = path.read_text(encoding="utf-8")
    assert "Generated by: testagent" in content
    assert "Target: shop::PricingService#finalPrice" in content
    assert '#include "shop/pricing_service.h"' in content
    assert "int main()" in content


def test_build_make_command_targets_testagent_make_rule(tmp_path: Path):
    test_file = tmp_path / "tests" / "testagent" / "generated" / "sample.cpp"
    report_dir = tmp_path / "reports"

    command = build_make_command(tmp_path, test_file, report_dir)

    assert command[0] == "make"
    assert "testagent-test" in command
    assert f"TEST_FILE={test_file}" in command
    assert any(arg.startswith("TEST_BINARY=") for arg in command)
    assert f"REPORT_DIR={report_dir}" in command
    assert any(arg.startswith("CXX=") and "--coverage" in arg for arg in command)


def test_sample_cpp_makefile_does_not_own_gcovr_coverage_generation():
    content = (PROJECT_ROOT / "under_test" / "sample-cpp-project" / "Makefile").read_text(
        encoding="utf-8",
    )

    assert "gcovr" not in content
    assert "coverage.xml" not in content


def test_parse_make_result_for_compile_error():
    output = "generated.cpp:4:5: error: use of undeclared identifier 'missing_symbol'\n"

    parsed = parse_make_result(2, output)

    assert parsed["compiled"] is False
    assert parsed["passed"] is False
    assert "missing_symbol" in parsed["compile_errors"]


def test_parse_make_result_for_runtime_failure():
    output = "Assertion failed: (actual == expected), function main, file generated.cpp, line 9.\n"

    parsed = parse_make_result(134, output)

    assert parsed["compiled"] is True
    assert parsed["passed"] is False
    assert parsed["failed_tests"] == ["main"]


def test_parse_make_result_for_success():
    parsed = parse_make_result(0, "")

    assert parsed["compiled"] is True
    assert parsed["passed"] is True
    assert parsed["failed_tests"] == []


@patch("testagent.executor.cpp.run_build", return_value=(0, ""))
def test_cpp_executor_runs_make_and_keeps_generated_test(mock_run, tmp_path: Path):
    (tmp_path / "Makefile").touch()
    executor = create_executor("cpp", tmp_path, reports_dir=tmp_path / "reports", keep_test=True)

    result = executor.execute(GeneratedTest(CPP_TEST_CODE, iteration=1), _context())

    assert result.compiled is True
    assert result.passed is True
    test_file = expected_test_file_path(tmp_path, "shop::PricingService", "finalPrice", 1)
    assert test_file.is_file()
    command = mock_run.call_args[0][1]
    assert "testagent-test" in command


def test_cpp_executor_reads_gcovr_coverage_when_xml_exists(tmp_path: Path):
    (tmp_path / "Makefile").touch()
    source_file = tmp_path / "src" / "pricing_service.cpp"
    source_file.parent.mkdir()
    source_file.write_text("double finalPrice() { return 0.0; }\n", encoding="utf-8")

    def fake_run_build(project_path, command, timeout=300):
        del project_path, timeout
        report_arg = next(arg for arg in command if arg.startswith("REPORT_DIR="))
        report_dir = Path(report_arg.split("=", 1)[1])
        report_dir.mkdir(parents=True, exist_ok=True)
        (report_dir / "coverage.xml").write_text(
            """\
<coverage line-rate="1.0" branch-rate="1.0">
  <packages>
    <package name="shop">
      <classes>
        <class name="pricing_service_cpp" filename="src/pricing_service.cpp"
               line-rate="1.0" branch-rate="1.0">
          <lines>
            <line number="1" hits="1" branch="false"/>
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
""",
            encoding="utf-8",
        )
        return 0, ""

    executor = create_executor("cpp", tmp_path, reports_dir=tmp_path / "reports", keep_test=True)
    context = _context()
    context.target.file_path = source_file

    with (
        patch("testagent.executor.cpp.run_build", side_effect=fake_run_build),
        patch("testagent.executor.cpp.run_gcovr", return_value=(0, "gcovr ok")),
    ):
        result = executor.execute(GeneratedTest(CPP_TEST_CODE, iteration=1), context)

    assert result.compiled is True
    assert result.coverage is not None
    assert result.coverage.line_coverage == pytest.approx(1.0)
    assert result.coverage.branch_coverage == pytest.approx(1.0)


@patch("testagent.executor.cpp.run_build", return_value=(0, ""))
def test_cpp_executor_generates_gcovr_xml_after_successful_build(mock_run, tmp_path: Path):
    (tmp_path / "Makefile").touch()
    source_file = tmp_path / "src" / "pricing_service.cpp"
    source_file.parent.mkdir()
    source_file.write_text("double finalPrice() { return 0.0; }\n", encoding="utf-8")

    def fake_run_gcovr(project_path, command, timeout=300):
        del project_path, timeout
        output_path = Path(command[command.index("--output") + 1])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            """\
<coverage line-rate="1.0" branch-rate="1.0">
  <packages>
    <package name="shop">
      <classes>
        <class name="pricing_service_cpp" filename="src/pricing_service.cpp"
               line-rate="1.0" branch-rate="1.0">
          <lines>
            <line number="1" hits="1" branch="false"/>
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
""",
            encoding="utf-8",
        )
        return 0, "gcovr ok"

    executor = create_executor("cpp", tmp_path, reports_dir=tmp_path / "reports", keep_test=True)
    context = _context()
    context.target.file_path = source_file

    with patch("testagent.executor.cpp.run_gcovr", side_effect=fake_run_gcovr) as mock_gcovr:
        result = executor.execute(GeneratedTest(CPP_TEST_CODE, iteration=1), context)

    assert result.compiled is True
    assert result.coverage is not None
    command = mock_gcovr.call_args[0][1]
    assert "--object-directory" in command
    assert str((tmp_path / "reports" / "shop_PricingService" / "finalPrice" / "iter1").resolve()) in command
    assert "src/.*" not in command


@patch("testagent.executor.cpp.run_build", return_value=(0, ""))
def test_cpp_executor_removes_generated_test_when_not_kept(mock_run, tmp_path: Path):
    (tmp_path / "Makefile").touch()
    executor = create_executor("cpp", tmp_path, reports_dir=tmp_path / "reports", keep_test=False)

    executor.execute(GeneratedTest(CPP_TEST_CODE, iteration=1), _context())

    test_file = expected_test_file_path(tmp_path, "shop::PricingService", "finalPrice", 1)
    assert not test_file.exists()
