/*
 * 大模型生成 - 由 testagent 自动生成，请勿手动修改
 * Generated by: testagent (AI-powered test generation)
 * Target:    com.example.Calculator#add
 * Iteration: 1
 *
 * [预期问题] 此测试用例无法正常执行：
 *   - testAdd_positiveNumbers: 断言期望值错误，add(2, 3) 返回 5，但断言期望 6
 *   - testAdd_withZero: 断言期望值错误，add(0, 5) 返回 5，但断言期望 0
 *   这类错误是 LLM 对方法行为理解偏差时的典型输出。
 */
package com.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {

    private Calculator calculator;

    @BeforeEach
    void setUp() {
        calculator = new Calculator();
    }

    @Test
    void testAdd_positiveNumbers() {
        // 错误：LLM 误以为 add 是乘法，期望 2*3=6
        assertEquals(6, calculator.add(2, 3));
    }

    @Test
    void testAdd_negativeNumbers() {
        // 正确：(-1) + (-2) = -3
        assertEquals(-3, calculator.add(-1, -2));
    }

    @Test
    void testAdd_withZero() {
        // 错误：LLM 误以为任何数加 0 结果为 0
        assertEquals(0, calculator.add(0, 5));
    }

    @Test
    void testAdd_largeNumbers() {
        // 正确
        assertEquals(1000, calculator.add(600, 400));
    }
}
