/*
 * 大模型生成 - 由 testagent 自动生成，请勿手动修改
 * Generated by: testagent (AI-powered test generation)
 * Target:    com.example.Calculator#divide
 * Iteration: 1
 *
 * [预期问题] 此测试用例存在分支未覆盖：
 *   Calculator.divide() 有两个分支：
 *     分支 A（已覆盖）：b != 0，正常执行除法并返回结果
 *     分支 B（未覆盖）：b == 0，抛出 ArithmeticException
 *   LLM 只生成了正常路径的测试，完全遗漏了异常分支。
 *   JaCoCo 报告中将显示第 9-11 行（if 体）为未覆盖，分支覆盖率 50%。
 */
package com.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {

    private Calculator calculator;

    @BeforeEach
    void setUp() {
        calculator = new Calculator();
    }

    @Test
    void testDivide_exactDivision() {
        assertEquals(5, calculator.divide(10, 2));
    }

    @Test
    void testDivide_resultIsOne() {
        assertEquals(1, calculator.divide(7, 7));
    }

    @Test
    void testDivide_dividendIsZero() {
        assertEquals(0, calculator.divide(0, 3));
    }

    @Test
    void testDivide_negativeNumbers() {
        assertEquals(-4, calculator.divide(-8, 2));
    }


}
