"""Build tool detection, test file injection, and command execution.

Responsibilities:
- Detect Maven vs Gradle from project layout
- Write the generated test file into the project's test source tree,
  prepending a "大模型生成" banner comment
- Construct and execute the build command (mvn / gradle)
- Return raw stdout+stderr and the return code for downstream parsing
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Build tool detection
# ---------------------------------------------------------------------------

_MAVEN_MARKERS = ("pom.xml",)
_GRADLE_MARKERS = ("build.gradle", "build.gradle.kts")


def detect_build_tool(project_path: Path) -> str:
    """Return ``"maven"`` or ``"gradle"`` based on project layout.

    Raises
    ------
    FileNotFoundError
        If neither ``pom.xml`` nor ``build.gradle[.kts]`` is found.
    """
    for marker in _MAVEN_MARKERS:
        if (project_path / marker).is_file():
            return "maven"
    for marker in _GRADLE_MARKERS:
        if (project_path / marker).is_file():
            return "gradle"
    raise FileNotFoundError(
        f"Neither pom.xml nor build.gradle found in {project_path}. "
        "Cannot detect build tool."
    )


# ---------------------------------------------------------------------------
# Test source directory
# ---------------------------------------------------------------------------

_TEST_SRC_CANDIDATES = (
    "src/test/java",
    "src/test",
)


def find_test_source_dir(project_path: Path) -> Path:
    """Return the root of the Java test source directory.

    Falls back to creating ``src/test/java`` if none exists.
    """
    for candidate in _TEST_SRC_CANDIDATES:
        d = project_path / candidate
        if d.is_dir():
            return d
    # Default: Maven convention
    return project_path / "src" / "test" / "java"


# ---------------------------------------------------------------------------
# Package / class name extraction from generated test code
# ---------------------------------------------------------------------------

def extract_package_from_code(test_code: str) -> str:
    """Return the package name declared in *test_code*, or empty string."""
    match = re.search(r"^\s*package\s+([\w.]+)\s*;", test_code, re.MULTILINE)
    return match.group(1) if match else ""


def extract_class_name_from_code(test_code: str) -> str:
    """Return the first top-level class name declared in *test_code*."""
    match = re.search(r"(?m)^\s*(?:public\s+)?class\s+(\w+)", test_code)
    if match:
        return match.group(1)
    raise ValueError("Cannot find class declaration in generated test code.")


# ---------------------------------------------------------------------------
# AI-generated banner comment
# ---------------------------------------------------------------------------

def _make_banner(class_name: str, method_name: str, iteration: int) -> str:
    return (
        "/*\n"
        " * 大模型生成 - 由 testagent 自动生成，请勿手动修改\n"
        " * Generated by: testagent (AI-powered test generation)\n"
        f" * Target:    {class_name}#{method_name}\n"
        f" * Iteration: {iteration}\n"
        " */\n"
    )


# ---------------------------------------------------------------------------
# Write test file
# ---------------------------------------------------------------------------

def write_test_file(
    test_code: str,
    project_path: Path,
    class_name: str,
    method_name: str,
    iteration: int,
) -> Path:
    """Write *test_code* into the project's test source tree.

    The file is placed at::

        <project>/src/test/java/<package_path>/<TestClass>.java

    A "大模型生成" banner is prepended before the package declaration so it
    is visible at the top of the file.

    Returns
    -------
    Path
        Absolute path to the written file.
    """
    package = extract_package_from_code(test_code)
    test_class = extract_class_name_from_code(test_code)

    test_src_root = find_test_source_dir(project_path)
    if package:
        dest_dir = test_src_root / Path(package.replace(".", "/"))
    else:
        dest_dir = test_src_root
    dest_dir.mkdir(parents=True, exist_ok=True)

    dest_file = dest_dir / f"{test_class}.java"

    banner = _make_banner(class_name, method_name, iteration)

    # Insert the banner before the package declaration (or at the top).
    pkg_match = re.search(r"^\s*package\s+[\w.]+\s*;", test_code, re.MULTILINE)
    if pkg_match:
        insert_pos = pkg_match.start()
        annotated = test_code[:insert_pos] + banner + test_code[insert_pos:]
    else:
        annotated = banner + test_code

    dest_file.write_text(annotated, encoding="utf-8")
    logger.info("Wrote test file: %s", dest_file)
    return dest_file


# ---------------------------------------------------------------------------
# Cleanup AI-generated test files
# ---------------------------------------------------------------------------

_BANNER_MARKER = "大模型生成"


def cleanup_generated_tests(
    project_path: Path,
    clean_marker: str = _BANNER_MARKER,
) -> list[Path]:
    """Remove test files from the project's test source tree.

    Parameters
    ----------
    project_path:
        Root of the Java project.
    clean_marker:
        Only delete ``.java`` files whose content contains this marker string.
        Defaults to ``"大模型生成"`` (the banner injected by :func:`write_test_file`).
        If set to an **empty string**, *all* ``.java`` files under the test
        source directory are deleted.

    Returns the list of deleted file paths.
    """
    test_src_root = find_test_source_dir(project_path)
    if not test_src_root.is_dir():
        logger.info("Test source dir does not exist: %s — nothing to clean.", test_src_root)
        return []

    delete_all = clean_marker == ""

    deleted: list[Path] = []
    for java_file in test_src_root.rglob("*.java"):
        if delete_all:
            java_file.unlink()
            logger.info("Deleted test file: %s", java_file)
            deleted.append(java_file)
            continue
        try:
            content = java_file.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            logger.warning("Cannot read %s: %s", java_file, exc)
            continue
        if clean_marker in content:
            java_file.unlink()
            logger.info("Deleted generated test: %s", java_file)
            deleted.append(java_file)

    # Prune empty directories left behind (bottom-up).
    for dirpath in sorted(test_src_root.rglob("*"), reverse=True):
        if dirpath.is_dir() and not any(dirpath.iterdir()):
            dirpath.rmdir()
            logger.debug("Removed empty directory: %s", dirpath)

    return deleted


# ---------------------------------------------------------------------------
# Build commands
# ---------------------------------------------------------------------------

def _resolve_mvn(project_path: Path) -> str:
    """Return 'mvn' or the project-local wrapper."""
    wrapper = project_path / "mvnw"
    return str(wrapper) if wrapper.is_file() else "mvn"


def _resolve_gradle(project_path: Path) -> str:
    """Return 'gradle' or the project-local wrapper."""
    wrapper = project_path / "gradlew"
    return str(wrapper) if wrapper.is_file() else "gradle"


def build_maven_command(
    project_path: Path,
    test_class_name: str,
    package: str,
    report_dir: Path,
) -> list[str]:
    """Construct the Maven command to run *test_class_name* and generate a JaCoCo report."""
    mvn = _resolve_mvn(project_path)
    fully_qualified = f"{package}.{test_class_name}" if package else test_class_name
    exec_file = report_dir / "jacoco.exec"
    return [
        mvn,
        "--batch-mode",
        "test",
        "jacoco:report",
        f"-Dtest={fully_qualified}",
        f"-Djacoco.destFile={exec_file}",
        f"-Djacoco.dataFile={exec_file}",
        f"-Djacoco.outputDirectory={report_dir}",
        "-DfailIfNoTests=false",
    ]


def build_gradle_command(
    project_path: Path,
    test_class_name: str,
    package: str,
    report_dir: Path,
) -> list[str]:
    """Construct the Gradle command to run *test_class_name* and generate a JaCoCo report."""
    gradle = _resolve_gradle(project_path)
    fully_qualified = f"{package}.{test_class_name}" if package else test_class_name
    exec_file = report_dir / "jacoco.exec"
    return [
        gradle,
        "test",
        "jacocoTestReport",
        f"--tests={fully_qualified}",
        # Pass report dir and exec file as project properties;
        # the build.gradle must honour them.
        f"-PjacocoReportDir={report_dir}",
        f"-PjacocoExecFile={exec_file}",
        "--continue",
    ]


# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------

def run_build(project_path: Path, command: list[str], timeout: int = 300) -> tuple[int, str]:
    """Run *command* in *project_path* and return ``(returncode, combined_output)``."""
    logger.info("Running build: %s", " ".join(command))
    result = subprocess.run(
        command,
        cwd=project_path,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout,
        text=True,
    )
    return result.returncode, result.stdout
